export * from './Nav/Nav';
export * from './Layout/Layout';
export * from './Heading/Heading';
export * from './Subheading/Subheading';
export * from './Project/Project';
export * from './Portfolio/Portfolio';
export * from './About/About';
export * from './Footer/Footer';
export * from './SubNav/SubNav';
